# general settings
name: Enhancement_RetinexFormer_LOL_v1_single
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data_single/LOLv1/Test/target
    dataroot_lq: data_single/LOLv1/Test/input
    io_backend:
      type: disk

# network structures
network_g:
  type: RetinexFormer
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1,2,2]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings (required for model initialization)
train:
  total_iter: 1
  warmup_iter: -1
  use_grad_clip: false
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [1]       
    restart_weights: [1]
    eta_mins: [0.0003]   
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true
  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 1e3
  save_img: true
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500 